// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVVVyrwHNEhtAGk-orbmxlH4dWYJ1KkX0',
    appId: '1:1036609858488:web:71bd490356525d405dfd4d',
    messagingSenderId: '1036609858488',
    projectId: 'fir-login-b0a01',
    authDomain: 'fir-login-b0a01.firebaseapp.com',
    storageBucket: 'fir-login-b0a01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtZXk1ARQOuADctLwClb4UB-h8_sQjWR4',
    appId: '1:1036609858488:android:c15dce90f33714225dfd4d',
    messagingSenderId: '1036609858488',
    projectId: 'fir-login-b0a01',
    storageBucket: 'fir-login-b0a01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsFzqb7g1yt4R5msCgrFT37a6YxDFilEU',
    appId: '1:1036609858488:ios:fce9e42411da5a295dfd4d',
    messagingSenderId: '1036609858488',
    projectId: 'fir-login-b0a01',
    storageBucket: 'fir-login-b0a01.firebasestorage.app',
    iosBundleId: 'com.example.miApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsFzqb7g1yt4R5msCgrFT37a6YxDFilEU',
    appId: '1:1036609858488:ios:fce9e42411da5a295dfd4d',
    messagingSenderId: '1036609858488',
    projectId: 'fir-login-b0a01',
    storageBucket: 'fir-login-b0a01.firebasestorage.app',
    iosBundleId: 'com.example.miApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVVVyrwHNEhtAGk-orbmxlH4dWYJ1KkX0',
    appId: '1:1036609858488:web:9a953d4f384bc56a5dfd4d',
    messagingSenderId: '1036609858488',
    projectId: 'fir-login-b0a01',
    authDomain: 'fir-login-b0a01.firebaseapp.com',
    storageBucket: 'fir-login-b0a01.firebasestorage.app',
  );
}
